call plug#begin('~/.vim/plugged')

Plug 'yegappan/lsp'
Plug 'altercation/vim-colors-solarized'

call plug#end()

let g:mapleader = " "
set rnu

syntax enable
set background=dark
colorscheme solarized

highlight SignColumn ctermbg=0
set laststatus=2
set noshowmode

function! DescriptiveMode()
  let l:mode_map = {
        \ 'n': 'NORMAL',
        \ 'no': 'NORMAL (operator pending)',
        \ 'v': 'VISUAL',
        \ 'V': 'VISUAL LINE',
        \ "\<C-v>": 'VISUAL BLOCK',
        \ 's': 'SELECT',
        \ 'S': 'SELECT LINE',
        \ "\<C-s>": 'SELECT BLOCK',
        \ 'i': 'INSERT',
        \ 'ic': 'INSERT (completion)',
        \ 'R': 'REPLACE',
        \ 'Rv': 'VIRTUAL REPLACE',
        \ 'c': 'COMMAND',
        \ 'cv': 'VIM EX',
        \ 'ce': 'EX',
        \ 'r': 'PROMPT',
        \ 'rm': 'MORE',
        \ 'r?': 'CONFIRM',
        \ '!': 'SHELL',
        \ 't': 'TERMINAL'
        \ }
  return get(l:mode_map, mode(), 'UNKNOWN')
endfunction

highlight StatusLineA ctermbg=14 ctermfg=15

set statusline=
set statusline+=%#StatusLineA#
set statusline+=\ %{DescriptiveMode()}
set statusline+=\ 
set statusline+=%#LineNr#
set statusline+=\ %t
set statusline+=%m
set statusline+=%=
set statusline+=\ %{&filetype}
set statusline+=\ 
set statusline+=%#StatusLineA#
set statusline+=\ %l:%c
set statusline+=\ 
set statusline+=%#LineNr#

let lspOpts = #{autoHighlightDiags: v:true}
autocmd User LspSetup call LspOptionsSet(lspOpts)

let lspServers = [#{
	\	  name: 'rustanalyzer',
	\	  filetype: ['rust'],
	\	  path: 'rust-analyzer',
	\	  args: []
	\ }]
autocmd User LspSetup call LspAddServer(lspServers)
