call plug#begin('~/.vim/plugged')

Plug 'yegappan/lsp'
Plug 'altercation/vim-colors-solarized'

call plug#end()

let g:mapleader = " "

syntax enable
set background=dark
colorscheme solarized

" set rnu
highlight SignColumn ctermbg=0
set laststatus=0

let lspOpts = #{autoHighlightDiags: v:true}
autocmd User LspSetup call LspOptionsSet(lspOpts)

let lspServers = [#{
	\	  name: 'rustanalyzer',
	\	  filetype: ['rust'],
	\	  path: 'rust-analyzer',
	\	  args: []
	\ }]
autocmd User LspSetup call LspAddServer(lspServers)
