return {
    "saghen/blink.cmp",
    dependencies = "rafamadriz/friendly-snippets",
    version = false,
    build = "cargo build --release",
    opts = {
        keymap = {
            ["<Tab>"] = { "accept", "fallback" },
        },
        completion = {
            accept = { auto_brackets = { enabled = true } },
            documentation = {
                auto_show = true,
            },
        },
        sources = {
            default = { "lsp", "path", "snippets", "buffer", "lazydev" },
            providers = {
                lazydev = { name = "LazyDev", module = "lazydev.integrations.blink", fallbacks = { "lsp" } },
            },
        },
        signature = {
            enabled = true,
        },
        appearance = {
            kind_icons = {
                Array = "",
                Boolean = "",
                Class = "",
                Color = "",
                Constant = "",
                Constructor = "",
                Enum = "",
                EnumMember = "",
                Event = "",
                Field = "",
                File = "",
                Folder = "",
                Function = "",
                Interface = "",
                Key = "",
                Keyword = "",
                Method = "",
                Module = "",
                Namespace = "",
                Null = "",
                Number = "",
                Object = "",
                Operator = "",
                Package = "",
                Property = "",
                Reference = "",
                Snippet = "",
                String = "",
                Struct = "",
                Text = "",
                TypeParameter = "",
                Unit = "",
                Value = "",
                Variable = "",
                Macro = "",
            },
        }
    },
}
